test_that("test.workbook.appendWorksheet", {
  wb.xls <- loadWorkbook("resources/testWorkbookAppend.xls")
  wb.xlsx <- loadWorkbook("resources/testWorkbookAppend.xlsx")
  appendWorksheet(wb.xls, mtcars, sheet = "mtcars")
  res <- readWorksheet(wb.xls, sheet = "mtcars")
  rownames(res) <- as.character(seq_len(nrow(res)))
  expect_equal(c(mtcars = 73), getLastRow(wb.xls, "mtcars"))
  expected_data_xls <- rbind(mtcars, mtcars)
  rownames(expected_data_xls) <- as.character(seq_len(nrow(expected_data_xls)))
  expect_equal(normalizeDataframe(expected_data_xls), normalizeDataframe(res))
  appendWorksheet(wb.xlsx, mtcars, sheet = "mtcars")
  res <- readWorksheet(wb.xlsx, sheet = "mtcars")
  rownames(res) <- as.character(seq_len(nrow(res)))
  expect_equal(c(mtcars = 73), getLastRow(wb.xlsx, "mtcars"))
  expected_data_xlsx <- rbind(mtcars, mtcars)
  rownames(expected_data_xlsx) <- as.character(seq_len(nrow(expected_data_xlsx)))
  expect_equal(normalizeDataframe(expected_data_xlsx), normalizeDataframe(res))
  expect_error(appendWorksheet(wb.xls, mtcars, sheet = "doesNotExist"), "IllegalArgumentException")
  expect_error(appendWorksheet(wb.xlsx, mtcars, sheet = "doesNotExist"), "IllegalArgumentException")
})
