test_that("test.workbook.isSheetVeryHidden", {
    wb.xls <- loadWorkbook("resources/testWorkbookHiddenSheets.xls"",
        create = FALSE)
    wb.xlsx <- loadWorkbook("resources/testWorkbookHiddenSheets.xlsx"",
        create = FALSE)
    expect_true(isSheetVeryHidden(wb.xls, 4))
    expect_true(isSheetVeryHidden(wb.xls, "DDD"))
    expect_false(isSheetVeryHidden(wb.xls, 1))
    expect_false(isSheetVeryHidden(wb.xls, "AAA"))
    expect_false(isSheetVeryHidden(wb.xls, 2))
    expect_false(isSheetVeryHidden(wb.xls, "BBB"))
    expect_false(isSheetVeryHidden(wb.xls, 3))
    expect_false(isSheetVeryHidden(wb.xls, "CCC"))
    expect_true(isSheetVeryHidden(wb.xlsx, 4))
    expect_true(isSheetVeryHidden(wb.xlsx, "DDD"))
    expect_false(isSheetVeryHidden(wb.xlsx, 1))
    expect_false(isSheetVeryHidden(wb.xlsx, "AAA"))
    expect_false(isSheetVeryHidden(wb.xlsx, 2))
    expect_false(isSheetVeryHidden(wb.xlsx, "BBB"))
    expect_false(isSheetVeryHidden(wb.xlsx, 3))
    expect_false(isSheetVeryHidden(wb.xlsx, "CCC"))
    expect_error(isSheetVeryHidden(wb.xls, 200))
    expect_error(isSheetVeryHidden(wb.xls, "Sheet does not exist"))
    expect_error(isSheetVeryHidden(wb.xls, "'Illegal sheet name"))
    expect_error(isSheetVeryHidden(wb.xlsx, 200))
    expect_error(isSheetVeryHidden(wb.xlsx, "Sheet does not exist"))
    expect_error(isSheetVeryHidden(wb.xlsx, "'Illegal sheet name"))
})

