test_that("test.workbook.existsName", {
    wb.xls <- loadWorkbook("resources/testWorkbookExistsNameAndSheet.xls"",
        create = FALSE)
    wb.xlsx <- loadWorkbook("resources/testWorkbookExistsNameAndSheet.xlsx"",
        create = FALSE)
    expect_found <- TRUE
    attributes(expect_found) <- list(worksheetScope = "")
    expect_equal(expect_found, existsName(wb.xls, "AA"))
    expect_equal(expect_found, existsName(wb.xls, "BB"))
    expect_equal(expect_found, existsName(wb.xls, "CC"))
    expect_equal(FALSE, existsName(wb.xls, "DD"))
    expect_equal(FALSE, existsName(wb.xls, "'illegal name"))
    expect_equal(FALSE, existsName(wb.xls, "%&$$-^~@afk20 235-??a?"))
    expect_equal(expect_found, existsName(wb.xlsx, "AA"))
    expect_equal(expect_found, existsName(wb.xlsx, "BB"))
    expect_equal(expect_found, existsName(wb.xlsx, "CC"))
    expect_equal(FALSE, existsName(wb.xlsx, "DD"))
    expect_equal(FALSE, existsName(wb.xlsx, "'illegal name"))
    expect_equal(FALSE, existsName(wb.xlsx, "%&$$-^~@afk20 235-??a?"))
    attributes(expect_found) <- list(worksheetScope = "AAA")
    expect_equal(expect_found, existsName(wb.xls, "AA_1"))
    attributes(expect_found) <- list(worksheetScope = "BBB")
    expect_equal(expect_found, existsName(wb.xls, "BB_1"))
    attributes(expect_found) <- list(worksheetScope = "AAA")
    expect_equal(expect_found, existsName(wb.xlsx, "AA_1"))
    attributes(expect_found) <- list(worksheetScope = "BBB")
    expect_equal(expect_found, existsName(wb.xlsx, "BB_1"))
    options(XLConnect.setCustomAttributes = FALSE)
    expect_true(existsName(wb.xls, "AA_1"))
    expect_true(existsName(wb.xls, "BB_1"))
    expect_true(existsName(wb.xlsx, "AA_1"))
    expect_true(existsName(wb.xlsx, "BB_1"))
    options(XLConnect.setCustomAttributes = TRUE)
})

