
name: dependency-install-test

# Check that installed JAR dependencies match the XLConnect (POI) transitive dependencies

on:
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["ci-tests"]
    # branches: [master, 'feature/**']
    types:
      - completed

jobs:
  install-check-pkg-deps:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Check installed JAR dependencies

    steps:
    - name: checkout XLConnect java
      uses: actions/checkout@v3
      with:
        repository: miraisolutions/xlconnect-java
        # specify the below if you are working on a paralllel xlconnect-java branch
        ref: bugfix/#181-poi_5_2_3-dependencies
    
    - name: retrieve dependencies using maven
      run: |
        ls -la
        mvn dependency:copy-dependencies
    
    - name: Download package
      uses: dawidd6/action-download-artifact@v2.24.2
      with:
        name: ubuntulatest-java17-Roldrel-results 
        path: .
        workflow: R
        # run_id: github.event.workflow_run.id
        run_id: 3481035224

    - name: Setup java (x64)
      uses: actions/setup-java@v1
      with:
        java-version: 17
        java-package: jdk
        architecture: x64

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
        use-public-rspm: true

    - name: run javareconf # Yes it actually needs JAVA_HOME=$JAVA_HOME, doesn't use actual env vars (!)
      run: |
        java -version
        echo java_home:$JAVA_HOME
        echo library paths: $LD_LIBRARY_PATH
        sudo R CMD javareconf JAVA_HOME=$JAVA_HOME
    
    - name: Install Package
      run: |
        install.packages("rJava",repos="https://cloud.r-project.org")
        install.packages(list.files(".", pattern = "XLConnect_.*.tar.gz", full.names = TRUE))

      shell: Rscript {0}

    - name: compare jar hashes
      run: | 
        set -eux -o pipefail
        XLC_JAR_PATH=$(Rscript -e "cat(.libPaths()[1])")/XLConnect/java
        find "$XLC_JAR_PATH" -maxdepth 1 -type f | grep -v -E "XLConnect" |\
        xargs -l sha512sum | sort | awk '{print $1}' > effective_hashes
        echo "computed actual hashes"
        cat effective_hashes
        find /home/runner/work/xlconnect/xlconnect/target/dependency/ -maxdepth 1 -type f |\
        grep -v -E "poi-ooxml-lite|junit|hamcrest" |\
        xargs -l sha512sum | sort | awk '{print $1}' > expected_hashes
        echo "computed expected hashes"
        cat expected_hashes
        cmp expected_hashes effective_hashes ||\
        (echo "JARs are different!" && ls -la /home/runner/work/xlconnect/xlconnect/target/dependency/ &&\
         ls -la "$XLC_JAR_PATH" &&\
         exit 1)
