
name: dependency-install-test

# Check that installed JAR dependencies match the XLConnect (POI) transitive dependencies

on:
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["ci-tests"]
    # branches: [master, 'feature/**']
    types:
      - completed

jobs:
  install-check-pkg-deps:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Check installed JAR dependencies

    steps:
    
    - name: Download package
      uses: dawidd6/action-download-artifact@v2.24.2
      with:
        name: ubuntulatest-java17-Roldrel-results 
        path: .
        workflow: R
        # run_id: github.event.workflow_run.id
        run_id: 3481035224

      - name: Setup java (x64)
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.config.java }}
          java-package: jdk
          architecture: x64
        if: matrix.config.os-name != 'macos' && matrix.config.java != 11

      - name: Set up R ${{ matrix.config.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r-version }}
          use-public-rspm: true
    
    - name: Install Package
      run: install.packages(list.files(".", pattern = "XLConnect_.*.tar.gz", full.names = TRUE))
      shell: Rscript {0}

    - name: checkout XLConnect java
      uses: actions/checkout@v3
      with:
        repository: miraisolutions/xlconnect-java
        # specify the below if you are working on a paralllel xlconnect-java branch
        # ref: feature/...
    
    - name: retrieve dependencies using maven
      run: mvn dependency:copy-dependencies
      working-directory: $GITHUB_WORKSPACE